### NumPy

In [1]:
# Importando o numpy
import numpy as np

In [2]:
np.__version__

'1.17.2'

#### Criando Arrays NumPy

**vetor**  = array de uma dimensão 
**matriz** = array de duas dimensoes
**tensor** = array de tres ou mais dimensões

In [7]:
# Help
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [8]:
# Array criado a partir de uma lista
vetor1 = np.array([0,1,2,3,4,5,6,7,8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

In [9]:
# Calculando a soma acumulada do array
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [10]:
# Imprimindo um elemento do vetor
vetor1[0]

0

In [11]:
# Alterando um elemento do vetor
vetor1[0] = 100

In [12]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [14]:
# Não é possivel incluir elementos de outro tipo no vetor numpy
vetor1[0] = "não é possivel"

ValueError: invalid literal for int() with base 10: 'não é possivel'

In [16]:
# Imprimindo o shape do vetor
vetor1.shape
#(9,) indica que ele é um array de apenas uma dimensão com 9 posicoes.

(9,)

#### Funções NumPy

In [19]:
# A função arange cria um vetor contendo uma progressao aritimética a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [21]:
vetor2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [24]:
# para saber o tipo de dado de um array
print(vetor2.dtype)

float64


In [25]:
x = np.arange(1, 10, 0.25)
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [26]:
# criando um array onde todos os valores sao ZERO. O numero dentro do parenteses é a quantidade de elementos do array
zeros = np.zeros(10)

print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
# o comando eye retorna 1 nos valores da diagonal e 0 nas demais. O valor entre parenteses é a quantidade de dimensoes
z = np.eye(3)

z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# No comando diag faz com que os valores passados no array como parametro formem uma diagonal.
# No exemplo abaixo o vetor (tensor) terá quatro dimensoes
d = np.diag(np.array([1,2,3,4]))

d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
# Array de numeros complexos
c = np.array([1+2j, 3+4j, 5+6*1j])
c

array([1.+2.j, 3.+4.j, 5.+6.j])