### Funções NumPy

In [1]:
import numpy as np

In [3]:
# assim como a função built-in range, é possivel criar um array com um determinado range
ex1 = np.arange(15)

ex1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
ex2 = np.arange(0, 10, 2)

ex2

array([0, 2, 4, 6, 8])

In [6]:
# Um array no range de 1 até 10 com intervalo de 0.25
ex3 = np.arange(1, 10, 0.25)

ex3

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [8]:
ex3.ndim

1

In [ ]:
ex3.