### Criando matrizes com NumPy

In [3]:
import numpy as np

In [18]:
matriz = np.array([[1,2,4], [4,5,6]])
matriz

array([[1, 2, 4],
       [4, 5, 6]])

In [5]:
matriz.ndim

2

In [10]:
# Criando uma matriz de duas dimensoes cada uma com quatro posicoes de valores zerados (dimensao, tamanho)
mZeros = np.zeros((2,4))

mZeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# Criando a mesma matriz de cima só que com valores 1
mOnes = np.ones((2,4))

mOnes

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
mOnes.shape

(2, 4)

In [13]:
# Retorna o total de elementos da matriz somando todos os elementos de todas as dimensoes
mOnes.itemsize

8

In [14]:
# Esse comando mostra o tamanho em bytes que esse array está ocupando na memoria
mOnes.nbytes

64

In [21]:
matriz = np.array([[1,2,4], [4,5,6]])
matriz

many = np.array([[0, 1, 2, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

many

array([list([0, 1, 2, 4, 5, 6, 7, 8, 9]),
       list([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])], dtype=object)

In [16]:
many[1,1]

IndexError: too many indices for array